# Generated by Django 5.0.2 on 2024-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
